# Generated by Django 3.0.3 on 2020-09-17 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='toDoList',
            new_name='todolist',
        ),
    ]
