# Generated by Django 3.0.3 on 2020-09-17 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beginning', '0002_sales'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Log',
        ),
    ]
